eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      
spring:
  profiles: persons
	personsData: [{"dni":"12345678","name":"Luis","lastName":"Vera"},
	{"dni":"98765432","name":"Mary Esther Daniela","lastName":"Ruiz Areas"},
	{"dni":"42534487","name":"Stivet Anthony","lastName":"Fulgencio Obando"},
	{"dni":"54657685","name":"Soledad","lastName":"Dionicio Zavaleta"},
	{"dni":"41678964","name":"Antonio","lastName":"Fulgencio Avila"}]

